parameters:
    version: '0.1.0'

services:
    PoP\PostTags\Conditional\API\RouteModuleProcessors\:
        resource: '../src/Conditional/API/RouteModuleProcessors/*'
        public: true

    PoP\PostTags\Conditional\RESTAPI\RouteModuleProcessors\:
        resource: '../src/Conditional/RESTAPI/RouteModuleProcessors/*'
        public: true
