services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\PostTags\Conditional\RESTAPI\Hooks\:
        resource: '../../../src/Conditional/RESTAPI/Hooks/*'
        public: true
